# Generated by Django 2.0.1 on 2020-05-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TNews',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(blank=True, null=True)),
                ('input_news_id', models.CharField(blank=True, max_length=30, null=True)),
                ('clip', models.CharField(blank=True, max_length=300, null=True)),
                ('press_release', models.CharField(blank=True, max_length=300, null=True)),
                ('images', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tnews',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tuser',
            },
        ),
        migrations.AddField(
            model_name='tnews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.TUser'),
        ),
    ]
