# Generated by Django 2.0.1 on 2020-05-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnews',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tuser',
            options={'managed': False},
        ),
    ]
